declare const styles:
  & Readonly<{ "calendar": string }>
  & Readonly<{ "calendarControls": string }>
  & Readonly<{ "calendarControlButton": string }>
  & Readonly<{ "calendarControlButton": string }>
  & Readonly<{ "calendarControlButton": string }>
  & Readonly<{ "calendarMonthHeader": string }>
  & Readonly<{ "calendarHeader": string }>
  & Readonly<{ "calendarHeaderDay": string }>
  & Readonly<{ "calendarRow": string }>
  & Readonly<{ "calendarDay": string }>
  & Readonly<{ "calendarDay": string }>
  & Readonly<{ "calendarDayThresholdHigh": string }>
  & Readonly<{ "calendarDayThresholdHigh": string }>
  & Readonly<{ "calendarDayThresholdHigh": string }>
  & Readonly<{ "calendarDayThresholdHigh": string }>
  & Readonly<{ "calendarDayThresholdMedium": string }>
  & Readonly<{ "calendarDayThresholdMedium": string }>
  & Readonly<{ "calendarDayThresholdMedium": string }>
  & Readonly<{ "calendarDayThresholdMedium": string }>
  & Readonly<{ "calendarDayThresholdLow": string }>
  & Readonly<{ "calendarDayThresholdLow": string }>
  & Readonly<{ "calendarDayThresholdLow": string }>
  & Readonly<{ "calendarDayThresholdLow": string }>
  & Readonly<{ "calendarDayThresholdLimited": string }>
  & Readonly<{ "calendarDayThresholdLimited": string }>
  & Readonly<{ "calendarDayThresholdLimited": string }>
  & Readonly<{ "calendarDayThresholdLimited": string }>
  & Readonly<{ "calendarDayAvailability": string }>
  & Readonly<{ "calendarDayAvailability": string }>
  & Readonly<{ "calendarDayAvailability": string }>
  & Readonly<{ "calendarDayAvailability": string }>
  & Readonly<{ "calendarDayAvailability": string }>
  & Readonly<{ "calendarDayAvailability": string }>
  & Readonly<{ "calendarDayAvailability": string }>
  & Readonly<{ "calendarDayAvailability": string }>
  & Readonly<{ "calendarDayAvailability": string }>
  & Readonly<{ "calendarDayAvailability": string }>
  & Readonly<{ "calendarDayInCurrentMonth": string }>
  & Readonly<{ "calendarDayInCurrentMonth": string }>
  & Readonly<{ "calendarDayInCurrentMonth": string }>
  & Readonly<{ "calendarDaySelected": string }>
  & Readonly<{ "calendarDaySelected": string }>
  & Readonly<{ "calendarDaySelected": string }>
  & Readonly<{ "calendarDaySelected": string }>
  & Readonly<{ "calendarDaySelected": string }>
  & Readonly<{ "calendarDayUnavailable": string }>
  & Readonly<{ "daySlots": string }>
  & Readonly<{ "daySlots": string }>
  & Readonly<{ "daySlots": string }>
  & Readonly<{ "center": string }>
  & Readonly<{ "right": string }>
  & Readonly<{ "daySlot": string }>
  & Readonly<{ "daySlot": string }>
  & Readonly<{ "daySlotAvailable": string }>
  & Readonly<{ "daySlotAvailable": string }>
  & Readonly<{ "daySlotSelected": string }>
  & Readonly<{ "timeSlotHeader": string }>
  & Readonly<{ "error": string }>
;
export default styles;
//# sourceMappingURL=./BookingFlowCalendar.module.css.d.ts.map
