import { __ } from '@wordpress/i18n';

// Unique translatable strings — scanned by wp i18n make-pot.
// prettier-ignore
// @ts-ignore: intentionally unused, exists for string extraction only
const translations = [ // eslint-disable-line @typescript-eslint/no-unused-vars
	__('15 Khordad Uprising', 'appointments-booking'),
	__('Adwa Victory Day', 'appointments-booking'),
	__('Afghanistan', 'appointments-booking'),
	__('Algeria', 'appointments-booking'),
	__('All Saints\' Day', 'appointments-booking'),
	__('Angola', 'appointments-booking'),
	__('Argentina', 'appointments-booking'),
	__('Armed Forces Day', 'appointments-booking'),
	__('Armistice Day', 'appointments-booking'),
	__('Army Day', 'appointments-booking'),
	__('Asalha Bucha Day', 'appointments-booking'),
	__('Ascension Day', 'appointments-booking'),
	__('Ash Wednesday', 'appointments-booking'),
	__('Ashura', 'appointments-booking'),
	__('Assumption of Mary', 'appointments-booking'),
	__('Autumnal Equinox Day', 'appointments-booking'),
	__('Baisakhi', 'appointments-booking'),
	__('Bangladesh', 'appointments-booking'),
	__('Bastille Day', 'appointments-booking'),
	__('Battle of Angamos Day', 'appointments-booking'),
	__('Battle of Boyacá Day', 'appointments-booking'),
	__('Bengali New Year (Pohela Boishakh)', 'appointments-booking'),
	__('Benito Juárez\'s Birthday', 'appointments-booking'),
	__('Black Consciousness Day', 'appointments-booking'),
	__('Boxing Day', 'appointments-booking'),
	__('Brazil', 'appointments-booking'),
	__('Buddha Jayanti', 'appointments-booking'),
	__('Buddha\'s Birthday', 'appointments-booking'),
	__('Buddhist Lent (Khao Phansa)', 'appointments-booking'),
	__('Canada', 'appointments-booking'),
	__('Canada Day', 'appointments-booking'),
	__('Carnival (Monday)', 'appointments-booking'),
	__('Carnival Tuesday', 'appointments-booking'),
	__('Children\'s Day', 'appointments-booking'),
	__('China', 'appointments-booking'),
	__('Chinese New Year', 'appointments-booking'),
	__('Chinese New Year (Day 2)', 'appointments-booking'),
	__('Chinese New Year (Day 3)', 'appointments-booking'),
	__('Christian Holidays', 'appointments-booking'),
	__('Christmas Day', 'appointments-booking'),
	__('Christmas Eve', 'appointments-booking'),
	__('Chuseok (Harvest Festival)', 'appointments-booking'),
	__('Colombia', 'appointments-booking'),
	__('Columbus Day', 'appointments-booking'),
	__('Coming of Age Day', 'appointments-booking'),
	__('Commemoration of Atatürk', 'appointments-booking'),
	__('Constitution Day', 'appointments-booking'),
	__('Constitution Memorial Day', 'appointments-booking'),
	__('Coronation Day', 'appointments-booking'),
	__('Corpus Christi', 'appointments-booking'),
	__('Culture Day', 'appointments-booking'),
	__('Dasara / Dussehra', 'appointments-booking'),
	__('Dashain (Vijaya Dashami)', 'appointments-booking'),
	__('Day of Defenders of Ukraine', 'appointments-booking'),
	__('Day of Europe', 'appointments-booking'),
	__('Day of Peace and National Reconciliation', 'appointments-booking'),
	__('Day of Reconciliation', 'appointments-booking'),
	__('Day of Remembrance for Truth and Justice', 'appointments-booking'),
	__('Death of Imam Khomeini', 'appointments-booking'),
	__('Declaration of Independence Day', 'appointments-booking'),
	__('Deepavali', 'appointments-booking'),
	__('Defender of the Fatherland Day', 'appointments-booking'),
	__('Democracy Day', 'appointments-booking'),
	__('Democracy and National Unity Day', 'appointments-booking'),
	__('Democratic Republic of the Congo', 'appointments-booking'),
	__('Diwali', 'appointments-booking'),
	__('Dormition of the Theotokos', 'appointments-booking'),
	__('Downfall of the Derg', 'appointments-booking'),
	__('Dragon Boat Festival', 'appointments-booking'),
	__('EDSA Revolution Anniversary', 'appointments-booking'),
	__('Early May Bank Holiday', 'appointments-booking'),
	__('Easter Monday', 'appointments-booking'),
	__('Easter Sunday', 'appointments-booking'),
	__('Egypt', 'appointments-booking'),
	__('Eid al-Adha', 'appointments-booking'),
	__('Eid al-Adha (Day 2)', 'appointments-booking'),
	__('Eid al-Adha (Day 3)', 'appointments-booking'),
	__('Eid al-Fitr', 'appointments-booking'),
	__('Eid al-Fitr (Day 2)', 'appointments-booking'),
	__('Eid al-Fitr (Day 3)', 'appointments-booking'),
	__('Emperor\'s Birthday', 'appointments-booking'),
	__('Epiphany', 'appointments-booking'),
	__('Ethiopia', 'appointments-booking'),
	__('Ethiopian Christmas (Genna)', 'appointments-booking'),
	__('Ethiopian Easter', 'appointments-booking'),
	__('Ethiopian Epiphany (Timkat)', 'appointments-booking'),
	__('Ethiopian New Year', 'appointments-booking'),
	__('Feast of Santa Rosa de Lima', 'appointments-booking'),
	__('Federal Territory Day', 'appointments-booking'),
	__('Finding of the True Cross (Meskel)', 'appointments-booking'),
	__('Flag Day', 'appointments-booking'),
	__('Founders\' Day', 'appointments-booking'),
	__('Founding Day', 'appointments-booking'),
	__('France', 'appointments-booking'),
	__('Freedom Day', 'appointments-booking'),
	__('Gandhi Jayanti', 'appointments-booking'),
	__('Ganesh Chaturthi', 'appointments-booking'),
	__('German Unity Day', 'appointments-booking'),
	__('Germany', 'appointments-booking'),
	__('Ghana', 'appointments-booking'),
	__('Good Friday', 'appointments-booking'),
	__('Green March Day', 'appointments-booking'),
	__('Greenery Day', 'appointments-booking'),
	__('Guru Nanak Jayanti', 'appointments-booking'),
	__('Hangul Day', 'appointments-booking'),
	__('Hanukkah', 'appointments-booking'),
	__('Hari Raya Haji (Eid al-Adha)', 'appointments-booking'),
	__('Hari Raya Puasa (Eid al-Fitr)', 'appointments-booking'),
	__('Heritage Day', 'appointments-booking'),
	__('Heroes\' Day', 'appointments-booking'),
	__('Hindu Holidays', 'appointments-booking'),
	__('Holi', 'appointments-booking'),
	__('Human Rights Day', 'appointments-booking'),
	__('Hung Kings Temple Festival', 'appointments-booking'),
	__('Immaculate Conception', 'appointments-booking'),
	__('Independence Day', 'appointments-booking'),
	__('Independence Movement Day', 'appointments-booking'),
	__('India', 'appointments-booking'),
	__('Indonesia', 'appointments-booking'),
	__('International Labour Day', 'appointments-booking'),
	__('International Women\'s Day', 'appointments-booking'),
	__('Iqbal Day', 'appointments-booking'),
	__('Iran', 'appointments-booking'),
	__('Iraq', 'appointments-booking'),
	__('Islamic New Year', 'appointments-booking'),
	__('Islamic Republic Day', 'appointments-booking'),
	__('Isra and Mi\'raj', 'appointments-booking'),
	__('Italy', 'appointments-booking'),
	__('Jamhuri Day (Independence Day)', 'appointments-booking'),
	__('Janmashtami (Krishna Jayanti)', 'appointments-booking'),
	__('Japan', 'appointments-booking'),
	__('Jewish Holidays', 'appointments-booking'),
	__('Juneteenth', 'appointments-booking'),
	__('Kenya', 'appointments-booking'),
	__('King\'s Birthday', 'appointments-booking'),
	__('Labor Day', 'appointments-booking'),
	__('Labour Day', 'appointments-booking'),
	__('Labour Thanksgiving Day', 'appointments-booking'),
	__('Laylat al-Qadr (Night of Power)', 'appointments-booking'),
	__('Liberation Day', 'appointments-booking'),
	__('Madaraka Day', 'appointments-booking'),
	__('Mahavira Jayanti', 'appointments-booking'),
	__('Makar Sankranti', 'appointments-booking'),
	__('Makha Bucha Day', 'appointments-booking'),
	__('Malaysia', 'appointments-booking'),
	__('Malaysia Day', 'appointments-booking'),
	__('Marine Day', 'appointments-booking'),
	__('Martin Luther King Jr. Day', 'appointments-booking'),
	__('Martyrs\' Day', 'appointments-booking'),
	__('Mashujaa Day (Heroes\' Day)', 'appointments-booking'),
	__('May Revolution Day', 'appointments-booking'),
	__('Memorial Day', 'appointments-booking'),
	__('Memory and Honour Day', 'appointments-booking'),
	__('Mexico', 'appointments-booking'),
	__('Mid-Autumn Festival', 'appointments-booking'),
	__('Morocco', 'appointments-booking'),
	__('Mountain Day', 'appointments-booking'),
	__('Mozambique', 'appointments-booking'),
	__('Muslim (Islamic) Holidays', 'appointments-booking'),
	__('Myanmar', 'appointments-booking'),
	__('Myanmar New Year', 'appointments-booking'),
	__('Nane Nane Day (Farmers\' Day)', 'appointments-booking'),
	__('National Day', 'appointments-booking'),
	__('National Day (Day 2)', 'appointments-booking'),
	__('National Day (Day 3)', 'appointments-booking'),
	__('National Day (Hari Merdeka)', 'appointments-booking'),
	__('National Day of Spain', 'appointments-booking'),
	__('National Foundation Day', 'appointments-booking'),
	__('National Heroes Day', 'appointments-booking'),
	__('National Heroes\' Day', 'appointments-booking'),
	__('National Sovereignty and Children\'s Day', 'appointments-booking'),
	__('National Unity Day', 'appointments-booking'),
	__('National Women\'s Day', 'appointments-booking'),
	__('Nature\'s Day (Sizdah Be-dar)', 'appointments-booking'),
	__('Navaratri (Sharad)', 'appointments-booking'),
	__('Navruz', 'appointments-booking'),
	__('Nepal', 'appointments-booking'),
	__('Nepali New Year (Nava Barsha)', 'appointments-booking'),
	__('New Year\'s Day', 'appointments-booking'),
	__('New Year\'s Eve', 'appointments-booking'),
	__('Nigeria', 'appointments-booking'),
	__('Ninoy Aquino Day', 'appointments-booking'),
	__('Nowruz (Day 2)', 'appointments-booking'),
	__('Nowruz (Day 3)', 'appointments-booking'),
	__('Nowruz (Day 4)', 'appointments-booking'),
	__('Nowruz (Persian New Year)', 'appointments-booking'),
	__('Nyepi (Balinese New Year)', 'appointments-booking'),
	__('Nyerere Day', 'appointments-booking'),
	__('Oil Nationalization Day', 'appointments-booking'),
	__('Orthodox Ascension Day', 'appointments-booking'),
	__('Orthodox Christian Holidays', 'appointments-booking'),
	__('Orthodox Christmas', 'appointments-booking'),
	__('Orthodox Easter Monday', 'appointments-booking'),
	__('Orthodox Easter Sunday', 'appointments-booking'),
	__('Orthodox Good Friday', 'appointments-booking'),
	__('Orthodox New Year (Old New Year)', 'appointments-booking'),
	__('Orthodox Palm Sunday', 'appointments-booking'),
	__('Orthodox Pentecost', 'appointments-booking'),
	__('Our Lady of Aparecida', 'appointments-booking'),
	__('Pakistan', 'appointments-booking'),
	__('Pakistan Day', 'appointments-booking'),
	__('Palm Sunday', 'appointments-booking'),
	__('Pancasila Day', 'appointments-booking'),
	__('Passover (Pesach)', 'appointments-booking'),
	__('Peace and Reconciliation Day', 'appointments-booking'),
	__('Peasants\' Day', 'appointments-booking'),
	__('Pentecost', 'appointments-booking'),
	__('Peru', 'appointments-booking'),
	__('Philippines', 'appointments-booking'),
	__('Poland', 'appointments-booking'),
	__('Presidents\' Day', 'appointments-booking'),
	__('Prithvi Jayanti & National Unity Day', 'appointments-booking'),
	__('Prophet\'s Birthday (Mawlid al-Nabi)', 'appointments-booking'),
	__('Purim', 'appointments-booking'),
	__('Quaid-e-Azam Day', 'appointments-booking'),
	__('Queen\'s Birthday', 'appointments-booking'),
	__('Raksha Bandhan', 'appointments-booking'),
	__('Ram Navami', 'appointments-booking'),
	__('Remembrance Day', 'appointments-booking'),
	__('Republic Day', 'appointments-booking'),
	__('Respect for the Aged Day', 'appointments-booking'),
	__('Reunification Day', 'appointments-booking'),
	__('Revolution Day', 'appointments-booking'),
	__('Revolution Day (December)', 'appointments-booking'),
	__('Rizal Day', 'appointments-booking'),
	__('Rosh Hashanah (Jewish New Year)', 'appointments-booking'),
	__('Russia', 'appointments-booking'),
	__('Russia Day', 'appointments-booking'),
	__('Saba Saba Day', 'appointments-booking'),
	__('Saudi Arabia', 'appointments-booking'),
	__('Second Day of Christmas', 'appointments-booking'),
	__('Seollal (Lunar New Year)', 'appointments-booking'),
	__('Shab-e-Barat', 'appointments-booking'),
	__('Sham El-Nessim', 'appointments-booking'),
	__('Shavuot', 'appointments-booking'),
	__('Showa Day', 'appointments-booking'),
	__('Simchat Torah', 'appointments-booking'),
	__('Simón Bolívar Day', 'appointments-booking'),
	__('Sinai Liberation Day', 'appointments-booking'),
	__('Songkran', 'appointments-booking'),
	__('South Africa', 'appointments-booking'),
	__('South Korea', 'appointments-booking'),
	__('Spain', 'appointments-booking'),
	__('Sports Day', 'appointments-booking'),
	__('Spring Bank Holiday', 'appointments-booking'),
	__('Spring and Labour Day', 'appointments-booking'),
	__('Start of Ramadan', 'appointments-booking'),
	__('Sudan', 'appointments-booking'),
	__('Sukkot', 'appointments-booking'),
	__('Summer Bank Holiday', 'appointments-booking'),
	__('Tanzania', 'appointments-booking'),
	__('Thailand', 'appointments-booking'),
	__('Thaipusam', 'appointments-booking'),
	__('Thanksgiving', 'appointments-booking'),
	__('Theophany (Orthodox Epiphany)', 'appointments-booking'),
	__('Thingyan (Water Festival)', 'appointments-booking'),
	__('Throne Day', 'appointments-booking'),
	__('Tihar (Diwali)', 'appointments-booking'),
	__('Tiradentes Day', 'appointments-booking'),
	__('Tomb Sweeping Day', 'appointments-booking'),
	__('Trinity Day (Whit Monday)', 'appointments-booking'),
	__('Turkey', 'appointments-booking'),
	__('Uganda', 'appointments-booking'),
	__('Ukraine', 'appointments-booking'),
	__('Unification Day', 'appointments-booking'),
	__('Union Day', 'appointments-booking'),
	__('United Kingdom', 'appointments-booking'),
	__('United States', 'appointments-booking'),
	__('Uzbekistan', 'appointments-booking'),
	__('Venezuela', 'appointments-booking'),
	__('Vernal Equinox Day', 'appointments-booking'),
	__('Vesak Day', 'appointments-booking'),
	__('Veterans Day', 'appointments-booking'),
	__('Victoria Day', 'appointments-booking'),
	__('Victory Day', 'appointments-booking'),
	__('Victory in Europe Day', 'appointments-booking'),
	__('Vietnam', 'appointments-booking'),
	__('Whit Monday', 'appointments-booking'),
	__('Women\'s Day', 'appointments-booking'),
	__('Yang di-Pertuan Agong\'s Birthday', 'appointments-booking'),
	__('Yemen', 'appointments-booking'),
	__('Yom Kippur', 'appointments-booking'),
	__('Youth Day', 'appointments-booking'),
	__('Youth and Sports Day', 'appointments-booking'),
];

const holidayNames: Record<string, string> = {
	newYear: "New Year's Day",
	newYearEve: "New Year's Eve",
	epiphany: 'Epiphany',
	mlkDay: 'Martin Luther King Jr. Day',
	presidentsDay: "Presidents' Day",
	ashWednesday: 'Ash Wednesday',
	palmSunday: 'Palm Sunday',
	goodFriday: 'Good Friday',
	easter: 'Easter Sunday',
	easterMonday: 'Easter Monday',
	labourDay: 'Labour Day',
	constitutionPL: 'Constitution Day',
	earlyMayBank: 'Early May Bank Holiday',
	victoryEurope: 'Victory in Europe Day',
	springBank: 'Spring Bank Holiday',
	memorialDay: 'Memorial Day',
	ascension: 'Ascension Day',
	juneteenth: 'Juneteenth',
	pentecost: 'Pentecost',
	whitMonday: 'Whit Monday',
	corpusChristi: 'Corpus Christi',
	independenceDayUS: 'Independence Day',
	bastilleDay: 'Bastille Day',
	assumptionOfMary: 'Assumption of Mary',
	summerBank: 'Summer Bank Holiday',
	laborDayUS: 'Labor Day',
	germanUnity: 'German Unity Day',
	columbusDay: 'Columbus Day',
	allSaints: "All Saints' Day",
	veteransDay: 'Veterans Day',
	independenceDayPL: 'Independence Day',
	armistice: 'Armistice Day',
	thanksgiving: 'Thanksgiving',
	christmas: 'Christmas Day',
	christmasEve: 'Christmas Eve',
	christmas2: 'Second Day of Christmas',
	boxingDay: 'Boxing Day',
	republicDayIN: 'Republic Day',
	independenceDayIN: 'Independence Day',
	gandhiJayanti: 'Gandhi Jayanti',
	holi: 'Holi',
	diwali: 'Diwali',
	dasara: 'Dasara / Dussehra',
	buddhaJayanti: 'Buddha Jayanti',
	mahaviraJayanti: 'Mahavira Jayanti',
	guruNanakJayanti: 'Guru Nanak Jayanti',
	chineseNewYear: 'Chinese New Year',
	chineseNewYear2: 'Chinese New Year (Day 2)',
	chineseNewYear3: 'Chinese New Year (Day 3)',
	tombSweepingDay: 'Tomb Sweeping Day',
	dragonBoatFestival: 'Dragon Boat Festival',
	midAutumnFestival: 'Mid-Autumn Festival',
	nationalDayCN: 'National Day',
	nationalDayCN2: 'National Day (Day 2)',
	nationalDayCN3: 'National Day (Day 3)',
	internationalWomensDay: "International Women's Day",
	eidAlFitr: 'Eid al-Fitr',
	eidAlFitr2: 'Eid al-Fitr (Day 2)',
	eidAlFitr3: 'Eid al-Fitr (Day 3)',
	eidAlAdha: 'Eid al-Adha',
	eidAlAdha2: 'Eid al-Adha (Day 2)',
	eidAlAdha3: 'Eid al-Adha (Day 3)',
	islamicNewYear: 'Islamic New Year',
	prophetBirthday: "Prophet's Birthday (Mawlid al-Nabi)",
	ramadanStart: 'Start of Ramadan',
	isra: "Isra and Mi'raj",
	independenceDayID: 'Independence Day',
	pancasilaDay: 'Pancasila Day',
	nyepi: 'Nyepi (Balinese New Year)',
	vesak: 'Vesak Day',
	independenceDayPK: 'Independence Day',
	pakistanDay: 'Pakistan Day',
	labourDayPK: 'Labour Day',
	iqbalDay: 'Iqbal Day',
	quaidAzamDay: 'Quaid-e-Azam Day',
	ashura: 'Ashura',
	independenceDayNG: 'Independence Day',
	democracyDayNG: 'Democracy Day',
	tiradentesDay: 'Tiradentes Day',
	independenceDayBR: 'Independence Day',
	ourLadyAparecida: 'Our Lady of Aparecida',
	republicDayBR: 'Republic Day',
	blackConsciousnessDay: 'Black Consciousness Day',
	carnival: 'Carnival (Monday)',
	carnival2: 'Carnival Tuesday',
	independenceDayBD: 'Independence Day',
	banglaNewYear: 'Bengali New Year (Pohela Boishakh)',
	victoryDayBD: 'Victory Day',
	shabbEBaraat: 'Shab-e-Barat',
	russiaDay: 'Russia Day',
	defenderOfFatherlandDay: 'Defender of the Fatherland Day',
	internationalWomensDay8: "International Women's Day",
	springLabourDay: 'Spring and Labour Day',
	victoryDayRU: 'Victory Day',
	nationalUnityDayRU: 'National Unity Day',
	independenceDayMX: 'Independence Day',
	revolutionDayMX: 'Revolution Day',
	constitutionDayMX: 'Constitution Day',
	benitoJuarezDay: "Benito Juárez's Birthday",
	ethiopianNewYear: 'Ethiopian New Year',
	meskel: 'Finding of the True Cross (Meskel)',
	ethiopianChristmas: 'Ethiopian Christmas (Genna)',
	ethiopianEpiphany: 'Ethiopian Epiphany (Timkat)',
	adwaVictoryDay: 'Adwa Victory Day',
	downfallDergET: 'Downfall of the Derg',
	ethiopianEasterET: 'Ethiopian Easter',
	orthodoxGoodFriday: 'Orthodox Good Friday',
	nationalFoundationDayJP: 'National Foundation Day',
	emperorsBirthdayJP: "Emperor's Birthday",
	showaDay: 'Showa Day',
	constitutionDayJP: 'Constitution Memorial Day',
	greeneryDay: 'Greenery Day',
	childrensDayJP: "Children's Day",
	marineDay: 'Marine Day',
	mountainDay: 'Mountain Day',
	respectForAgedDay: 'Respect for the Aged Day',
	autumnEquinox: 'Autumnal Equinox Day',
	healthSportsDay: 'Sports Day',
	cultureDay: 'Culture Day',
	labourThanksgivingDay: 'Labour Thanksgiving Day',
	vernalEquinox: 'Vernal Equinox Day',
	comingOfAgeDay: 'Coming of Age Day',
	independenceDayPH: 'Independence Day',
	ninoyAquinoDay: 'Ninoy Aquino Day',
	nationalHeroesDayPH: 'National Heroes Day',
	bondingOfRizal: 'Rizal Day',
	edsa: 'EDSA Revolution Anniversary',
	revolutionDayEG: 'Revolution Day',
	nationalDayEG: 'National Day',
	shamElNessim: 'Sham El-Nessim',
	sinaiLiberationEG: 'Sinai Liberation Day',
	labourDayEG: 'Labour Day',
	independenceDayCD: 'Independence Day',
	liberationDayVN: 'Reunification Day',
	internationalLabourDayVN: 'International Labour Day',
	nationalDayVN: 'National Day',
	hungKingsDay: 'Hung Kings Temple Festival',
	islamicRepublicDayIR: 'Islamic Republic Day',
	natureDayIR: "Nature's Day (Sizdah Be-dar)",
	revolutionDayIR: 'Revolution Day',
	nowruz: 'Nowruz (Persian New Year)',
	nowruz2: 'Nowruz (Day 2)',
	nowruz3: 'Nowruz (Day 3)',
	nowruz4: 'Nowruz (Day 4)',
	oilNationalizationIR: 'Oil Nationalization Day',
	deathKhomeini: 'Death of Imam Khomeini',
	khordadUprisingIR: '15 Khordad Uprising',
	republicDayTR: 'Republic Day',
	nationalSovereigntyTR: "National Sovereignty and Children's Day",
	ataturkDay: 'Commemoration of Atatürk',
	victoryDayTR: 'Victory Day',
	youthSportsDayTR: 'Youth and Sports Day',
	democracyDayTR: 'Democracy and National Unity Day',
	tanzaniaUnionDay: 'Union Day',
	independenceDayTZ: 'Independence Day',
	nyerereDayTZ: 'Nyerere Day',
	sababaDayTZ: 'Saba Saba Day',
	navaDayTZ: "Nane Nane Day (Farmers' Day)",
	humanRightsDayZA: 'Human Rights Day',
	freedomDayZA: 'Freedom Day',
	youthDayZA: 'Youth Day',
	nationalWomensDayZA: "National Women's Day",
	heritageDayZA: 'Heritage Day',
	dayOfReconciliation: 'Day of Reconciliation',
	republicDayIT: 'Republic Day',
	liberationDayIT: 'Liberation Day',
	immaculateConception: 'Immaculate Conception',
	independenceDayMM: 'Independence Day',
	unionDayMM: 'Union Day',
	peasantsDayMM: "Peasants' Day",
	armedForcesDayMM: 'Armed Forces Day',
	thingyanMM: 'Thingyan (Water Festival)',
	songkranTH: 'Songkran',
	europeDayUA: 'Day of Europe',
	myanmarNewYear: 'Myanmar New Year',
	martyrsDayMM: "Martyrs' Day",
	nationalDayMM: 'National Day',
	jamhuri: 'Jamhuri Day (Independence Day)',
	mashujaaDay: "Mashujaa Day (Heroes' Day)",
	madaraka: 'Madaraka Day',
	liberationDayKR: 'Liberation Day',
	chuseok: 'Chuseok (Harvest Festival)',
	seollal: 'Seollal (Lunar New Year)',
	constitutionDayKR: 'Constitution Day',
	nationalFoundationDayKR: 'National Foundation Day',
	hangulDay: 'Hangul Day',
	buddhasBirthdayKR: "Buddha's Birthday",
	childrensDayKR: "Children's Day",
	memorialDayKR: 'Memorial Day',
	independenceDayCO: 'Independence Day',
	battleOfBoyaca: 'Battle of Boyacá Day',
	hispanityDayES: 'National Day of Spain',
	constitutionDayES: 'Constitution Day',
	immaculateConcepcionES: 'Immaculate Conception',
	independenceDayUG: 'Independence Day',
	liberationDayUG: 'Liberation Day',
	martyrsDayUG: "Martyrs' Day",
	heroesDay: "Heroes' Day",
	independenceDayAR: 'Independence Day',
	mayRevolutionAR: 'May Revolution Day',
	flagDayAR: 'Flag Day',
	independenceDayDZ: 'Independence Day',
	revolutionDayDZ: 'Revolution Day',
	independenceDaySD: 'Independence Day',
	revolutionDaySD: 'Revolution Day (December)',
	nationalDayIQ: 'National Day',
	republicDayIQ: 'Republic Day',
	armyDayIQ: 'Army Day',
	independenceDayAF: 'Independence Day',
	canadaDay: 'Canada Day',
	victoriaDay: 'Victoria Day',
	thanksgivingCA: 'Thanksgiving',
	remembranceDay: 'Remembrance Day',
	throneDay: 'Throne Day',
	greenMarchDay: 'Green March Day',
	independenceDayMA: 'Independence Day',
	youthDayMA: 'Youth Day',
	labourDayMA: 'Labour Day',
	nationalDaySA: 'National Day',
	foundingDaySA: 'Founding Day',
	independenceDayUA: 'Independence Day',
	constitutionDayUA: 'Constitution Day',
	defendersDay: 'Day of Defenders of Ukraine',
	orthodoxChristmas: 'Orthodox Christmas',
	orthodoxEaster: 'Orthodox Easter Sunday',
	orthodoxEasterMonday: 'Orthodox Easter Monday',
	trinityDay: 'Trinity Day (Whit Monday)',
	independenceDayUZ: 'Independence Day',
	constitutionDayUZ: 'Constitution Day',
	memoryAndHonourDay: 'Memory and Honour Day',
	navruz: 'Navruz',
	independenceDayPE: 'Independence Day',
	peruArmedForces: 'Armed Forces Day',
	battleOfAngamos: 'Battle of Angamos Day',
	santaRosaLima: 'Feast of Santa Rosa de Lima',
	independenceDayAO: 'Independence Day',
	victoryDayAO: 'Victory Day',
	peaceDayAO: 'Day of Peace and National Reconciliation',
	heroesOfAngolaDay: "National Heroes' Day",
	malaysiaDayMY: 'Malaysia Day',
	federalTerritoryDayMY: 'Federal Territory Day',
	independenceDayMY: 'National Day (Hari Merdeka)',
	agongBirthday: "Yang di-Pertuan Agong's Birthday",
	hariRayaPuasa: 'Hari Raya Puasa (Eid al-Fitr)',
	hariRayaHaji: 'Hari Raya Haji (Eid al-Adha)',
	thaipusamMY: 'Thaipusam',
	deepavali: 'Deepavali',
	independenceDayMZ: 'Independence Day',
	herosDayMZ: "Heroes' Day",
	peaceDayMZ: 'Peace and Reconciliation Day',
	victoryDayMZ: 'Victory Day',
	womensDayMZ: "Women's Day",
	independenceDayGH: 'Independence Day',
	republicDayGH: 'Republic Day',
	revolutionDayGH: 'Revolution Day',
	foundersDayGH: "Founders' Day",
	independenceDayYE: 'Independence Day',
	unificationDayYE: 'Unification Day',
	constitutionDayNP: 'Constitution Day',
	prithviJayanti: 'Prithvi Jayanti & National Unity Day',
	martyrsDayNP: "Martyrs' Day",
	democracyDayNP: 'Democracy Day',
	tihar: 'Tihar (Diwali)',
	dashainNP: 'Dashain (Vijaya Dashami)',
	nepaleseNewYear: 'Nepali New Year (Nava Barsha)',
	independenceDayVE: 'Independence Day',
	bolivarDay: 'Simón Bolívar Day',
	independenceDayVE2: 'Declaration of Independence Day',
	independenceMovementDayKR: 'Independence Movement Day',
	dayOfRemembranceAR: 'Day of Remembrance for Truth and Justice',
	coronationDayTH: 'Coronation Day',
	queensBirthdayTH: "Queen's Birthday",
	kingsBirthdayTH: "King's Birthday",
	constitutionDayTH: 'Constitution Day',
	nationalDayTH: 'National Day',
	makhaRucha: 'Makha Bucha Day',
	asakhaRucha: 'Asalha Bucha Day',
	khaoPhansa: 'Buddhist Lent (Khao Phansa)',
	orthodoxNewYear: 'Orthodox New Year (Old New Year)',
	theophany: 'Theophany (Orthodox Epiphany)',
	orthodoxPalmSunday: 'Orthodox Palm Sunday',
	orthodoxAscension: 'Orthodox Ascension Day',
	orthodoxPentecost: 'Orthodox Pentecost',
	dormitionOfTheotokos: 'Dormition of the Theotokos',
	laylatalQadr: 'Laylat al-Qadr (Night of Power)',
	makarSankranti: 'Makar Sankranti',
	baisakhi: 'Baisakhi',
	ramNavami: 'Ram Navami',
	janamashtami: 'Janmashtami (Krishna Jayanti)',
	ganeshChaturthi: 'Ganesh Chaturthi',
	navaratri: 'Navaratri (Sharad)',
	rakshabandhan: 'Raksha Bandhan',
	roshHashanah: 'Rosh Hashanah (Jewish New Year)',
	yomKippur: 'Yom Kippur',
	sukkot: 'Sukkot',
	passover: 'Passover (Pesach)',
	shavuot: 'Shavuot',
	hanukkah: 'Hanukkah',
	purim: 'Purim',
	simchatTorah: 'Simchat Torah',
};

const groupNames: Record<string, string> = {
	AF: 'Afghanistan',
	AO: 'Angola',
	AR: 'Argentina',
	BD: 'Bangladesh',
	BR: 'Brazil',
	CA: 'Canada',
	CD: 'Democratic Republic of the Congo',
	CN: 'China',
	CO: 'Colombia',
	DE: 'Germany',
	DZ: 'Algeria',
	EG: 'Egypt',
	ES: 'Spain',
	ET: 'Ethiopia',
	FR: 'France',
	GB: 'United Kingdom',
	GH: 'Ghana',
	ID: 'Indonesia',
	IN: 'India',
	IQ: 'Iraq',
	IR: 'Iran',
	IT: 'Italy',
	JP: 'Japan',
	KE: 'Kenya',
	KR: 'South Korea',
	MA: 'Morocco',
	MM: 'Myanmar',
	MX: 'Mexico',
	MY: 'Malaysia',
	MZ: 'Mozambique',
	NG: 'Nigeria',
	NP: 'Nepal',
	PE: 'Peru',
	PH: 'Philippines',
	PK: 'Pakistan',
	PL: 'Poland',
	RU: 'Russia',
	SA: 'Saudi Arabia',
	SD: 'Sudan',
	TH: 'Thailand',
	TR: 'Turkey',
	TZ: 'Tanzania',
	UA: 'Ukraine',
	UG: 'Uganda',
	US: 'United States',
	UZ: 'Uzbekistan',
	VE: 'Venezuela',
	VN: 'Vietnam',
	YE: 'Yemen',
	ZA: 'South Africa',
	christian: 'Christian Holidays',
	hindu: 'Hindu Holidays',
	jewish: 'Jewish Holidays',
	muslim: 'Muslim (Islamic) Holidays',
	orthodox: 'Orthodox Christian Holidays',
};

export function getHolidayName(ref: string): string {
	const name = holidayNames[ref];
	return name ? __(name, 'appointments-booking') : ref;
}

export function getGroupName(id: string): string {
	const name = groupNames[id];
	return name ? __(name, 'appointments-booking') : id;
}
